/**
 * Emit the whole dataset as idempotent SQL on stdout.
 *
 *   npx tsx scripts/db/seed-sql.ts | psql "$SUPABASE_DB_URL"
 *
 * Why SQL rather than the REST client: seeding over plain Postgres needs only a
 * connection string, so provisioning takes one secret instead of four, and it
 * does not depend on the schema being exposed to PostgREST first. The REST path
 * (`npm run db:push`) still exists for local use.
 *
 * The output is one transaction. Either the whole dataset lands or none of it
 * does — a half-seeded schema serving partial charts would be worse than an
 * empty one, because it would look fine.
 */
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { Series, Source, DevEvent } from "../../lib/types";

const ROOT = process.cwd();
const SERIES_FILES = [
  "data/series/defence.json",
  "data/series/infrastructure.json",
  "data/series/economy.json",
  "data/series/space.json",
  "data/series/wdi.json",
];

/** Postgres string literal. Doubling single quotes is the only escape needed. */
function q(v: string | null | undefined): string {
  if (v === null || v === undefined) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

function n(v: number | null | undefined): string {
  return v === null || v === undefined || !Number.isFinite(v) ? "NULL" : String(v);
}

function b(v: boolean | null | undefined): string {
  return v === null || v === undefined ? "NULL" : v ? "true" : "false";
}

/** text[] literal, e.g. ARRAY['a','b'] — empty arrays need an explicit cast. */
function arr(items: string[] | undefined): string {
  if (!items || items.length === 0) return "'{}'::text[]";
  return `ARRAY[${items.map(q).join(",")}]::text[]`;
}

async function readJson<T>(rel: string): Promise<T> {
  return JSON.parse(await readFile(join(ROOT, rel), "utf8")) as T;
}

async function main() {
  const sources = await readJson<Source[]>("data/sources.json");
  const series: Series[] = [];
  for (const f of SERIES_FILES) series.push(...(await readJson<Series[]>(f)));
  const events = await readJson<DevEvent[]>("data/events.json");

  const out: string[] = [];
  const w = (s: string) => out.push(s);

  w("-- Generated by scripts/db/seed-sql.ts. Do not edit by hand.");
  w("BEGIN;");
  w("SET LOCAL search_path = bharat_tracker, public;");
  w("");

  w("-- Sources -------------------------------------------------------------");
  for (const s of sources) {
    w(
      `INSERT INTO bharat_tracker.sources (id,name,publisher,url,provenance,accessed,tier,updated_at) VALUES (` +
        `${q(s.id)},${q(s.name)},${q(s.publisher)},${q(s.url)},${q(s.provenance)},${q(s.accessed)},${s.tier},now())` +
        ` ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,publisher=EXCLUDED.publisher,url=EXCLUDED.url,` +
        `provenance=EXCLUDED.provenance,accessed=EXCLUDED.accessed,tier=EXCLUDED.tier,updated_at=now();`,
    );
  }
  w("");

  w("-- Series --------------------------------------------------------------");
  for (const s of series) {
    w(
      `INSERT INTO bharat_tracker.series (id,title,definition,category,unit,unit_short,frequency,` +
        `higher_is_better,provenance,confidence,last_verified,notes,source_ids,updated_at) VALUES (` +
        `${q(s.id)},${q(s.title)},${q(s.definition)},${q(s.category)},${q(s.unit)},${q(s.unitShort)},` +
        `${q(s.frequency)},${b(s.higherIsBetter)},${q(s.provenance)},${q(s.confidence)},${q(s.lastVerified)},` +
        `${arr(s.notes)},${arr(s.sourceIds)},now())` +
        ` ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,definition=EXCLUDED.definition,` +
        `category=EXCLUDED.category,unit=EXCLUDED.unit,unit_short=EXCLUDED.unit_short,` +
        `frequency=EXCLUDED.frequency,higher_is_better=EXCLUDED.higher_is_better,` +
        `provenance=EXCLUDED.provenance,confidence=EXCLUDED.confidence,last_verified=EXCLUDED.last_verified,` +
        `notes=EXCLUDED.notes,source_ids=EXCLUDED.source_ids,updated_at=now();`,
    );
  }
  w("");

  // Points and peers are replaced wholesale: upstream revisions delete and
  // renumber periods, so merging would leave stale rows behind.
  // Batched multi-row INSERTs rather than one statement per row: ~1,700 points
  // as individual statements is half a megabyte of SQL, which is awkward to
  // paste into a SQL editor and slow to execute one round-trip at a time.
  function batched(table: string, columns: string, rows: string[], size = 250) {
    for (let i = 0; i < rows.length; i += size) {
      const chunk = rows.slice(i, i + size);
      w(`INSERT INTO ${table} (${columns}) VALUES`);
      w(chunk.map((r, j) => `  ${r}${j === chunk.length - 1 ? ";" : ","}`).join("\n"));
    }
  }

  w("-- Data points ---------------------------------------------------------");
  w("DELETE FROM bharat_tracker.data_points;");
  w("DELETE FROM bharat_tracker.series_peers;");

  const pointRows: string[] = [];
  const peerRows: string[] = [];
  for (const s of series) {
    s.points.forEach((p, i) => {
      pointRows.push(
        `(${q(s.id)},${q(p.period)},${n(p.value)},${q(p.sourceId)},${p.revised ? "true" : "false"},${q(p.note)},${i})`,
      );
    });
    for (const p of s.peers ?? []) {
      peerRows.push(
        `(${q(s.id)},${q(p.iso3)},${q(p.country)},${n(p.value)},${q(p.period)},${q(p.sourceId)})`,
      );
    }
  }
  batched("bharat_tracker.data_points", "series_id,period,value,source_id,revised,note,ordinal", pointRows);
  batched("bharat_tracker.series_peers", "series_id,iso3,country,value,period,source_id", peerRows);
  w("");

  w("-- Development events --------------------------------------------------");
  for (const e of events) {
    w(
      `INSERT INTO bharat_tracker.events (id,title,category,date,place_id,place_name,state,lon,lat,` +
        `outlet,url,summary,status) VALUES (` +
        `${q(e.id)},${q(e.title)},${q(e.category)},${q(e.date)},${q(e.placeId)},${q(e.placeName)},` +
        `${q(e.state)},${n(e.coords?.[0] ?? null)},${n(e.coords?.[1] ?? null)},${q(e.outlet)},${q(e.url)},` +
        `${q(e.summary)},${q(e.status)})` +
        ` ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title,category=EXCLUDED.category,date=EXCLUDED.date,` +
        `place_id=EXCLUDED.place_id,place_name=EXCLUDED.place_name,state=EXCLUDED.state,lon=EXCLUDED.lon,` +
        `lat=EXCLUDED.lat,outlet=EXCLUDED.outlet,url=EXCLUDED.url,summary=EXCLUDED.summary,status=EXCLUDED.status;`,
    );
  }
  w("");
  w("COMMIT;");
  w("");
  w("\\echo '--- seeded ---'");
  w(
    "SELECT (SELECT count(*) FROM bharat_tracker.sources) AS sources," +
      " (SELECT count(*) FROM bharat_tracker.series) AS series," +
      " (SELECT count(*) FROM bharat_tracker.data_points) AS data_points," +
      " (SELECT count(*) FROM bharat_tracker.series_peers) AS peers," +
      " (SELECT count(*) FROM bharat_tracker.events) AS events;",
  );

  process.stdout.write(out.join("\n") + "\n");
}

main().catch((err: unknown) => {
  process.stderr.write((err instanceof Error ? err.stack : String(err)) + "\n");
  process.exit(1);
});
