/**
 * The geography the Blender scene is built from.
 *
 * Writes a plain GeoJSON of the countries around the Line of Control, plus the
 * sites named in the Sindoor book with the coordinates that connector resolved
 * from Wikipedia. Blender's Python cannot read TopoJSON and should not be
 * asked to — the scene script's job is to draw what it is given, so that every
 * shape on the rendered page traces back to Natural Earth and every marker
 * traces back to a cited page.
 *
 * Nothing here decides where a border runs. The Line of Control is disputed
 * and Natural Earth draws it as one line among several possible; the scene
 * labels it as a line on a map rather than as a settled boundary, which is the
 * same thing the rest of this site does with it.
 */
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { feature } from "topojson-client";
import type { FeatureCollection, Geometry } from "geojson";

const ATLAS = join(process.cwd(), "node_modules", "world-atlas", "countries-10m.json");
const BOOK = join(process.cwd(), "data", "defence", "sindoor-book.json");

/** ISO 3166-1 numeric, which is what the atlas joins on. */
const WANT: Record<string, string> = {
  "356": "India", "586": "Pakistan", "004": "Afghanistan", "156": "China",
  "064": "Bhutan", "524": "Nepal", "368": "Iraq", "364": "Iran", "762": "Tajikistan",
};

interface Placed { id: string; name: string; town?: string; position: { lat: number; lon: number } | null }

function main(): void {
  const topo = JSON.parse(readFileSync(ATLAS, "utf8")) as Parameters<typeof feature>[0];
  const obj = (topo as { objects: Record<string, unknown> }).objects["countries"];
  const fc = feature(topo, obj as never) as unknown as FeatureCollection<Geometry, { name?: string }>;

  const kept = fc.features.filter((f) => WANT[String(f.id).padStart(3, "0")] !== undefined)
    .map((f) => ({
      type: "Feature" as const,
      id: String(f.id).padStart(3, "0"),
      properties: { name: WANT[String(f.id).padStart(3, "0")] ?? String(f.properties?.name ?? "") },
      geometry: f.geometry,
    }));

  const book = JSON.parse(readFileSync(BOOK, "utf8")) as {
    targets?: Placed[]; airbases?: Placed[];
  };
  const sites = [
    ...(book.targets ?? []).map((t) => ({ ...t, kind: "camp" as const })),
    ...(book.airbases ?? []).map((a) => ({ ...a, kind: "base" as const })),
  ].filter((s): s is Placed & { kind: "camp" | "base"; position: { lat: number; lon: number } } =>
    s.position !== null && Number.isFinite(s.position.lat) && Number.isFinite(s.position.lon));

  const out = join(process.cwd(), "scripts", "blender", "scene-input.json");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify({
    note:
      "Generated by scripts/blender/export-geo.ts. Country shapes are Natural Earth via "
      + "world-atlas at 10m. Site positions come from the Sindoor book connector, which resolves "
      + "each named place against Wikipedia rather than accepting a typed latitude.",
    countries: { type: "FeatureCollection", features: kept },
    sites,
  }) + "\n", "utf8");

  console.log(`Wrote ${out}: ${kept.length} countries, ${sites.length} placed sites.`);
  if (sites.length === 0) {
    console.log("No sites placed yet — run the sindoor:book workflow first, which resolves coordinates.");
  }
}

main();
