"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  RAMP, rampIndexByRank, runsOf,
  type AsciiGrid, type LayerSummary, type RefusedLayer, type StateItems,
} from "@/lib/state-layers-shared";

/**
 * India, drawn in characters, that answers a click.
 *
 * ── Why characters ───────────────────────────────────────────────────────
 *
 * Because the encoding is honest at any size and in any medium. Every cell
 * carries the reading twice — once as colour and once as the weight of the
 * glyph in it — so the map survives being printed, being read by someone who
 * cannot separate the blues, and being looked at on a phone where the colour
 * steps are three pixels apart. A choropleth carries it once.
 *
 * It is also not decoration. The grid is the same topology every other map on
 * this site draws, sampled by point-in-polygon at roughly sixty kilometres a
 * cell, generated by scripts/geo/build-ascii-india.ts and committed. The three
 * union territories too small to catch a sample point at that resolution are
 * named under the map rather than quietly missing from it.
 *
 * ── What a click does ────────────────────────────────────────────────────
 *
 * Choose a layer, click a state, and the panel names what is in it and what
 * the record says about each one — not a count, and not a tooltip that
 * disappears when you move the mouse to read it. Each row carries the basis
 * for its claim, because "one of the twelve Jyotirlingas" from a tradition's
 * own list and "dedicated to Shiva" guessed from a temple's name are not the
 * same kind of statement and a panel that prints them identically is lying
 * quietly.
 *
 * ── Ranked, not scaled ───────────────────────────────────────────────────
 *
 * The counts are brutally skewed — Tamil Nadu holds 969 temples, a dozen
 * states hold fewer than ten. A linear ramp paints the entire country at the
 * floor and two states at the top: true, and unreadable. The ramp is spread
 * over rank instead, and the real number is printed the instant anyone asks
 * for one, which is the trade a map should make and a table should not.
 *
 * ── Performance ──────────────────────────────────────────────────────────
 *
 * Six thousand cells, but a row crosses only a handful of states, so the map
 * is a few hundred runs rather than six thousand nodes. Pointer position maps
 * to a cell by arithmetic — no hit-testing, no per-cell listeners.
 */

/**
 * Ten glyph rungs, five colour rungs.
 *
 * The glyph carries the fine gradation, so the colour only has to carry the
 * direction — which lets the ramp be the legible half of the hue family rather
 * than the whole of it. The whole of it was the first version: --seq-100 is a
 * very pale blue in the light theme and a very dark one in the dark theme, and
 * in each case the states at that rung disappeared into the page. A state
 * nobody can see reads as no data, not as little data. See --ascii-* in
 * globals.css for the contrast figures.
 */
const SEQ = ["--ascii-1", "--ascii-1", "--ascii-2", "--ascii-2", "--ascii-3",
  "--ascii-3", "--ascii-4", "--ascii-4", "--ascii-5", "--ascii-5"] as const;

export default function AsciiIndia({
  grid, layers, refused,
}: {
  grid: AsciiGrid;
  layers: LayerSummary[];
  refused: RefusedLayer[];
}) {
  const [layerId, setLayerId] = useState(layers[0]?.id ?? "");
  const [hover, setHover] = useState<string | null>(null);
  const [picked, setPicked] = useState<string | null>(null);
  const [items, setItems] = useState<StateItems | null>(null);
  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);
  const svgRef = useRef<SVGSVGElement>(null);

  const layer = layers.find((l) => l.id === layerId) ?? layers[0];
  const rows = useMemo(() => runsOf(grid), [grid]);
  const rank = useMemo(() => rampIndexByRank(layer?.counts ?? {}), [layer]);
  const CH = grid.cellAspect;

  // Every state the grid can draw, for the keyboard control. A pointer map
  // with no equivalent is a map half the readers cannot use.
  const states = useMemo(
    () => [...new Set(Object.values(grid.symbols))].sort((a, b) => a.localeCompare(b)),
    [grid],
  );

  useEffect(() => {
    if (!picked || !layer) { setItems(null); return; }
    let live = true;
    setLoading(true); setFailed(false);
    fetch(`/api/state-layer?layer=${encodeURIComponent(layer.id)}&state=${encodeURIComponent(picked)}`)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((d: StateItems) => { if (live) setItems(d); })
      .catch(() => { if (live) setFailed(true); })
      .finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
  }, [picked, layer]);

  /** Cell under the pointer, by arithmetic against the viewBox. */
  const stateAtPointer = useCallback((clientX: number, clientY: number): string | null => {
    const el = svgRef.current;
    if (!el) return null;
    const b = el.getBoundingClientRect();
    if (b.width === 0 || b.height === 0) return null;
    const col = Math.floor(((clientX - b.left) / b.width) * grid.cols);
    const row = Math.floor(((clientY - b.top) / b.height) * grid.rows);
    const ch = grid.grid[row]?.[col];
    if (!ch || ch === "." || ch === "?") return null;
    return grid.symbols[ch] ?? null;
  }, [grid]);

  const count = picked ? layer?.counts[picked] ?? 0 : null;

  return (
    <div className="ascii-hero relative">
      {/* ── The layer chips ───────────────────────────────────────────── */}
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="eyebrow mr-1">Show</span>
        {layers.map((l) => (
          <button
            key={l.id}
            type="button"
            onClick={() => { setLayerId(l.id); }}
            aria-pressed={l.id === layerId}
            className="glass rounded-full px-3 py-1 text-[12px] transition-colors"
            style={{
              color: l.id === layerId ? "var(--surface-1)" : "var(--text-secondary)",
              background: l.id === layerId ? "var(--text-primary)" : undefined,
              borderColor: l.id === layerId ? "transparent" : undefined,
            }}
          >
            {l.label}
            <span className="mono ml-1.5 text-[10.5px] opacity-70">{l.placed}</span>
          </button>
        ))}
      </div>

      <div className="relative mt-4">
        {/* The wash behind the glass. Two theme colours at low alpha: glass
            with nothing behind it is a grey box. */}
        <div aria-hidden className="ascii-wash" />

        {/*
          Sized from its height, not its width.

          The grid is taller than it is wide — 103 columns against 119 rows of
          user units, because fitting the island territories into the frame
          makes it so. Sized to the container's width the map came out around
          eleven hundred pixels tall and ran off the bottom of the screen with
          the panel below the fold. Driving the size from a viewport-relative
          height and letting the width follow the ratio keeps the whole country
          and the panel over it in view, and `max-width: 100%` hands control
          back to the width on a phone, where the height is not the constraint.
        */}
        <svg
          ref={svgRef}
          viewBox={`0 0 ${grid.cols} ${grid.rows * CH}`}
          style={{ height: "min(58vh, 34rem)", width: "auto", maxWidth: "100%" }}
          className="relative mx-auto block cursor-crosshair select-none"
          role="img"
          aria-label={`India by state, shaded by ${layer?.label.toLowerCase() ?? "layer"}. Use the state list below to open one.`}
          onPointerMove={(e) => setHover(stateAtPointer(e.clientX, e.clientY))}
          onPointerLeave={() => setHover(null)}
          onClick={(e) => {
            const s = stateAtPointer(e.clientX, e.clientY);
            if (s) setPicked((p) => (p === s ? null : s));
          }}
        >
          {rows.map((runs, r) => (
            <g key={r}>
              {runs.map((run) => {
                if (!run.state) {
                  // Sea, and unnamed land. Both are drawn — a gap would make
                  // the coastline ragged for a reason nobody could see.
                  return (
                    <text
                      key={run.col}
                      x={run.col} y={(r + 0.8) * CH}
                      textLength={run.text.length} lengthAdjust="spacingAndGlyphs"
                      fontSize={CH} fontFamily="var(--font-mono)"
                      fill="var(--gridline)" opacity={0.5}
                    >
                      {run.text.replace(/./g, run.text[0] === "?" ? "·" : "·")}
                    </text>
                  );
                }
                const idx = rank[run.state] ?? 0;
                const isOn = hover === run.state || picked === run.state;
                const dim = picked !== null && picked !== run.state && hover !== run.state;
                return (
                  <text
                    key={run.col}
                    x={run.col} y={(r + 0.8) * CH}
                    textLength={run.text.length} lengthAdjust="spacingAndGlyphs"
                    fontSize={CH} fontFamily="var(--font-mono)"
                    fill={isOn ? "var(--text-primary)" : `var(${SEQ[idx] ?? "--seq-100"})`}
                    opacity={dim ? 0.5 : 1}
                    style={{ transition: "opacity .16s, fill .16s" }}
                  >
                    {RAMP[idx]!.repeat(run.text.length)}
                  </text>
                );
              })}
            </g>
          ))}
        </svg>

        {/* ── The glass panel ───────────────────────────────────────────
            Over the Bay of Bengal on a wide screen, which is the empty half
            of the frame the island territories put there, and beneath the map
            on a narrow one where there is no empty half. */}
        <div className="pointer-events-none absolute inset-x-0 bottom-0 hidden lg:block">
          <div className="pointer-events-auto ml-auto w-[19rem] max-w-[46%]">
            <Panel
              picked={picked} count={count} layer={layer} items={items}
              loading={loading} failed={failed} onClose={() => setPicked(null)}
            />
          </div>
        </div>
      </div>

      {/* Keyboard and small-screen route into the same thing. */}
      <div className="mt-3 flex flex-wrap items-center gap-2">
        <label className="eyebrow" htmlFor="ascii-state">State</label>
        <select
          id="ascii-state"
          value={picked ?? ""}
          onChange={(e) => setPicked(e.target.value || null)}
          className="glass rounded-md px-2 py-1 text-[12.5px]"
        >
          <option value="">— choose one —</option>
          {states.map((s) => (
            <option key={s} value={s}>
              {s}{layer?.counts[s] ? ` (${layer.counts[s]})` : ""}
            </option>
          ))}
        </select>
        {hover && !picked && (
          <span className="mono text-[11.5px] text-[color:var(--text-muted)]">
            {hover} · {layer?.counts[hover] ?? 0}
          </span>
        )}
      </div>

      <div className="mt-3 lg:hidden">
        <Panel
          picked={picked} count={count} layer={layer} items={items}
          loading={loading} failed={failed} onClose={() => setPicked(null)}
        />
      </div>

      {/* ── What the map cannot tell you ─────────────────────────────── */}
      <div className="mt-4 space-y-1.5 text-[11.5px] leading-[1.6] text-[color:var(--text-muted)]">
        {layer && (
          <p>
            <span className="text-[color:var(--text-secondary)]">{layer.label}:</span>{" "}
            {layer.blurb} {layer.join}{" "}
Shading is by rank, not by count — {layer.placed} of {layer.total} placed
            {layer.unplacedCount > 0 && <>, {layer.unplacedCount} the join could not put in a state</>}
            {layer.deduped > 0 && <>, {layer.deduped} collapsed as a duplicate of a row already counted</>}.
          </p>
        )}
        {grid.unsampled.length > 0 && (
          <p>
            A cell is about sixty kilometres across, which is too coarse to catch{" "}
            {grid.unsampled.join(", ")}. They are missing from the picture rather than
            empty in it.
          </p>
        )}
        {refused.map((r) => (
          <p key={r.layer}>
            <span className="text-[color:var(--text-secondary)]">Not a layer here — {r.layer}:</span>{" "}
            {r.why}
          </p>
        ))}
      </div>
    </div>
  );
}

/** The state panel, in both places it appears. */
function Panel({
  picked, count, layer, items, loading, failed, onClose,
}: {
  picked: string | null;
  count: number | null;
  layer: LayerSummary | undefined;
  items: StateItems | null;
  loading: boolean;
  failed: boolean;
  onClose: () => void;
}) {
  if (!picked) {
    return (
      <div className="glass rounded-lg p-3.5">
        <p className="text-[12.5px] leading-[1.6] text-[color:var(--text-secondary)]">
          Click a state — or pick one below — to see what is in it, named.
        </p>
      </div>
    );
  }
  return (
    <div className="glass rounded-lg">
      <div className="flex items-start gap-2 border-b border-[color:var(--hairline)] px-3.5 py-2.5">
        <div className="min-w-0 flex-1">
          <p className="text-[13.5px] font-semibold leading-tight">{picked}</p>
          <p className="mono mt-0.5 text-[10.5px] uppercase tracking-[0.08em] text-[color:var(--text-muted)]">
            {count ?? 0} {layer?.label.toLowerCase() ?? ""}
          </p>
        </div>
        <button
          type="button" onClick={onClose} aria-label="Close"
          className="-mr-1 shrink-0 rounded p-1 text-[color:var(--text-muted)] hover:text-[color:var(--text-primary)]"
        >
          <svg width="11" height="11" viewBox="0 0 11 11" aria-hidden>
            <path d="M1 1l9 9M10 1l-9 9" stroke="currentColor" strokeWidth="1.4" fill="none" />
          </svg>
        </button>
      </div>

      <div className="max-h-[15rem] overflow-y-auto px-3.5 py-2.5">
        {loading && <p className="text-[12px] text-[color:var(--text-muted)]">Reading…</p>}
        {failed && (
          <p className="text-[12px] leading-[1.55] text-[color:var(--text-secondary)]">
            The list did not load. That is this page failing to fetch, not a statement that the
            state holds nothing.
          </p>
        )}
        {!loading && !failed && items && items.items.length === 0 && (
          <p className="text-[12px] leading-[1.55] text-[color:var(--text-secondary)]">
            Nothing in this layer reaches {picked}. For the airports and metro layers that means
            no row fell inside its polygon; it is not a claim that none exists.
          </p>
        )}
        {!loading && !failed && items && items.items.length > 0 && (
          <>
            <ul className="m-0 list-none space-y-2 p-0">
              {items.items.map((it) => (
                <li key={`${it.name}-${it.lat ?? 0}`} className="border-b border-[color:var(--hairline)] pb-2 last:border-b-0">
                  <p className="text-[12.5px] font-medium leading-snug">{it.name}</p>
                  <p className="mt-0.5 text-[11.5px] leading-[1.5] text-[color:var(--text-secondary)]">
                    {it.why}
                  </p>
                  <p className="mono mt-0.5 text-[10px] leading-[1.4] text-[color:var(--text-muted)]">
                    {it.basis}
                  </p>
                </li>
              ))}
            </ul>
            {items.truncated && (
              <p className="mt-2 text-[11px] text-[color:var(--text-muted)]">
                Showing {items.items.length} of {items.total}. The rest are in the dataset, not on
                this panel.
              </p>
            )}
          </>
        )}
      </div>
    </div>
  );
}
